name: "Pull Request Linter"
description: "Ensure your PR titles match a given regex."
author: "MorrisonCole"
branding:
  icon: "check"
  color: "green"
inputs:
  title-regex:
    description: "Regex to ensure PR title matches. Allows anything by default."
    required: true
    default: ".*"
  body-regex:
    description: "Regex to ensure PR body matches. Allows anything by default."
    required: true
    default: ".*"
  on-failed-regex-create-review:
    description:
      "Whether the action should create a PR review & comment when the title regex
      doesn't match."
    required: false
    default: true
  on-failed-body-regex-create-review:
    description:
      "Whether the action should create a PR review & comment when the body regex
      doesn't match."
    required: false
    default: true
  on-failed-regex-comment:
    description:
      "Comment for the bot to post on PRs that fail the title regex. Use %regex% to
      reference regex."
    required: false
    default: "PR title failed to match %regex%"
  on-failed-body-regex-comment:
    description:
      "Comment for the bot to post on PRs that fail the body regex. Use %regex% to
      reference regex."
    required: false
    default: "PR body failed to match %regex%"
  on-failed-regex-fail-action:
    description: "Whether the action should fail when the title regex doesn't match."
    required: false
    default: false
  on-failed-body-regex-fail-action:
    description: "Whether the action should fail when the body regex doesn't match."
    required: false
    default: false
  on-failed-regex-request-changes:
    description:
      "Whether the action should request changes or just provide a comment."
    required: false
    default: true
  on-failed-body-regex-request-changes:
    description:
      "Whether the action should request changes or just provide a comment."
    required: false
    default: true
  on-succeeded-regex-dismiss-review-comment:
    description:
      "Comment for the bot to post on PRs that succeed the regex and have their
      review dismissed."
    required: false
    default: "All good!"
  repo-token:
    description:
      "Github token with access to the repository (secrets.GITHUB_TOKEN)."
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
