name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn --immutable
          yarn build
          yarn package
          git add lib/ dist/
          git diff-index --quiet HEAD || git commit -m "ci: generate build"
          git push
